module.exports = {
  products: [
    {
      _id: 1,
      category: "Brewed Coffees",
      title: "Kick Frappe",
      excerpt: "Topped with whipped cream and indulgent Coffee Drizzle",
      price: 2.9,
      priceDiscount: 0,
      stock: 10,
      rating: 1,
      liked: false,
      imgUrl: "espresso.png",
    },
    {
      _id: 2,
      category: "Bakery",
      title: "Chocolate muffin",
      excerpt: "A rich chocolate muffin with a creamy caramel center",
      price: 4.7,
      priceDiscount: 2.9,
      stock: 4,
      rating: 3,
      liked: true,
      imgUrl: "chocolate-muffin.png",
    },
    {
      _id: 3,
      category: "Cold Brews",
      title: "Iced Coffee",
      excerpt: "Freshly brewed, served chilled and sweetened over ice",
      price: 2.9,
      priceDiscount: 0,
      stock: 7,
      rating: 1,
      liked: false,
      imgUrl: "iced-coffee.png",
    },
    {
      _id: 4,
      category: "Lunch",
      title: "Chicken veggie Pie",
      excerpt:
        "Made with tender 100% chicken and baked fresh in store every day",
      price: 4.8,
      priceDiscount: 3.45,
      stock: 0,
      rating: 4,
      liked: false,
      imgUrl: "chicken-veggie-pie.png",
    },
    {
      _id: 5,
      category: "Bakery",
      title: "Chocolate Chip Cookie",
      excerpt:
        "This scrumptious, satisfying cookie chocolate chips embedded in a thick dough",
      price: 1.8,
      priceDiscount: 0,
      stock: 3,
      rating: 5,
      liked: false,
      imgUrl: "chocolate-chip-cookie.png",
    },
    {
      _id: 6,
      category: "Creme Frappuccino",
      title: "Hot Chocolate",
      excerpt:
        "Made with tender 100% chicken and baked fresh in store every day",
      price: 3.4,
      priceDiscount: 2.95,
      stock: 10,
      rating: 3,
      liked: false,
      imgUrl: "hot-chocolate.png",
    },
    {
      _id: 7,
      category: "Coffee Frappuccino",
      title: "Caramel Apple Spice",
      excerpt:
        "Steamed apple juice with cinnamon syrup, whipped cream and a caramel sauce drizzle",
      price: 4.8,
      priceDiscount: 3.45,
      stock: 2,
      rating: 4,
      liked: false,
      imgUrl: "caramel-apple-spice.png",
    },
    {
      _id: 8,
      category: "Hot Coffees",
      title: "Cocoa Cloud Macchiato",
      excerpt:
        "Our Cloud Macchiato: light and airy with layers of fluffy foam*, cascading espresso, flavored toffee nut syrup",
      price: 3.8,
      priceDiscount: 3.25,
      stock: 2,
      rating: 2,
      liked: true,
      imgUrl: "cocoa-cloud-macchiato.png",
    },
  ],
};
