module.exports = {
  products: [
    {
      _id: 1,
      category: "Brew",
      title: "Kick Frappe",
      excerpt: "Topped with whipped cream and indulgent Coffee Drizzle",
      price: 2.9,
      priceDiscount: 0,
      stock: 10,
      rating: 0,
      liked: false,
      imgUrl: "espresso.png",
    },
    {
      _id: 2,
      category: "Brew",
      title: "Chocolate muffin",
      excerpt: "A rich chocolate muffin with a creamy caramel center",
      price: 4.7,
      priceDiscount: 2.9,
      stock: 4,
      rating: 3,
      liked: true,
      imgUrl: "chocolate-muffin.png",
    },
    {
      _id: 3,
      category: "Brew",
      title: "Iced Coffee",
      excerpt: "Freshly brewed, served chilled and sweetened over ice",
      price: 2.9,
      priceDiscount: 0,
      stock: 7,
      rating: 0,
      liked: false,
      imgUrl: "iced-coffee.png",
    },
    {
      _id: 4,
      category: "Brew",
      title: "Chicken veggie Pie",
      excerpt:
        "Made with tender 100% chicken and baked fresh in store every day",
      price: 4.8,
      priceDiscount: 3.45,
      stock: 0,
      rating: 4,
      liked: false,
      imgUrl: "chicken-veggie-pie.png",
    },
  ],
};
